// vue-frontend/src/components/layout/Navigation.vue
<template>
  <div class="flex min-h-screen bg-gray-50">
    <!-- Sidebar -->
    <nav class="sidebar glass-dark fixed h-full z-50 transition-all duration-300 border-r border-white/10" :class="{ 'collapsed': sidebarCollapsed }">
      <!-- Sidebar Header -->
      <div class="sidebar-header p-6 border-b border-white/10">
        <div class="flex items-center">
          <div class="sidebar-brand flex items-center">
            <div class="brand-icon gradient-secondary rounded-2xl flex items-center justify-center mr-4 shadow-lg"
                 style="width: 48px; height: 48px;">
              <ShieldCheckIcon class="text-white w-6 h-6" />
            </div>
            <div v-if="!sidebarCollapsed" class="brand-text">
              <h1 class="font-bold text-xl text-white">Admin Panel</h1>
              <p class="text-white/60 text-sm">Management System</p>
            </div>
          </div>
          <button 
            class="text-white/80 p-2 ml-auto lg:hidden hover:text-white hover:bg-white/10 rounded-xl transition-all duration-200"
            @click="toggleSidebar"
          >
            <XMarkIcon class="w-6 h-6" />
          </button>
        </div>
      </div>

      <!-- Navigation Menu -->
      <div class="sidebar-content flex-grow overflow-auto py-6">
        <div class="px-4 space-y-2">
          <!-- Dashboard -->
          <div class="nav-item">
            <router-link 
              to="/dashboard" 
              class="nav-link group flex items-center rounded-2xl px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-300 relative overflow-hidden"
              :class="{ 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-white border border-white/20': $route.path === '/dashboard' }"
            >
              <div class="nav-icon-wrapper p-2 rounded-xl bg-white/10 mr-4 group-hover:bg-white/20 transition-all duration-300">
                <HomeIcon class="w-5 h-5" />
              </div>
              <span v-if="!sidebarCollapsed" class="font-medium">Dashboard</span>
              <div v-if="$route.path === '/dashboard'" class="absolute right-2 w-2 h-2 bg-white rounded-full"></div>
            </router-link>
          </div>

          <!-- Users -->
          <div class="nav-item" v-if="hasPermission('view users')">
            <router-link 
              to="/users" 
              class="nav-link group flex items-center rounded-2xl px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-300 relative overflow-hidden"
              :class="{ 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-white border border-white/20': $route.path === '/users' }"
            >
              <div class="nav-icon-wrapper p-2 rounded-xl bg-white/10 mr-4 group-hover:bg-white/20 transition-all duration-300">
                <UsersIcon class="w-5 h-5" />
              </div>
              <span v-if="!sidebarCollapsed" class="font-medium">Users</span>
              <div v-if="$route.path === '/users'" class="absolute right-2 w-2 h-2 bg-white rounded-full"></div>
            </router-link>
          </div>

          <!-- Roles -->
          <div class="nav-item" v-if="hasPermission('view roles' )">
            <router-link 
              to="/roles" 
              class="nav-link group flex items-center rounded-2xl px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-300 relative overflow-hidden"
              :class="{ 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-white border border-white/20': $route.path === '/roles' }"
            >
              <div class="nav-icon-wrapper p-2 rounded-xl bg-white/10 mr-4 group-hover:bg-white/20 transition-all duration-300">
                <UserGroupIcon class="w-5 h-5" />
              </div>
              <span v-if="!sidebarCollapsed" class="font-medium">Roles</span>
              <div v-if="$route.path === '/roles'" class="absolute right-2 w-2 h-2 bg-white rounded-full"></div>
            </router-link>
          </div>

          <!-- Permissions -->
          <div class="nav-item" v-if="hasPermission('view permissions')">
            <router-link 
              to="/permissions" 
              class="nav-link group flex items-center rounded-2xl px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-300 relative overflow-hidden"
              :class="{ 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-white border border-white/20': $route.path === '/permissions' }"
            >
              <div class="nav-icon-wrapper p-2 rounded-xl bg-white/10 mr-4 group-hover:bg-white/20 transition-all duration-300">
                <KeyIcon class="w-5 h-5" />
              </div>
              <span v-if="!sidebarCollapsed" class="font-medium">Permissions</span>
              <div v-if="$route.path === '/permissions'" class="absolute right-2 w-2 h-2 bg-white rounded-full"></div>
            </router-link>
          </div>

          <!-- Profile -->
        </div>
      </div>

      <!-- User Profile Section -->
      <div class="sidebar-footer border-t border-white/10 p-4">
        <div class="relative">
          <button 
            class="w-full text-left flex items-center hover:bg-white/10 rounded-2xl px-4 py-3 transition-all duration-300 group"
            @click="toggleUserMenu"
          >
            <div class="user-avatar gradient-primary rounded-2xl flex items-center justify-center mr-4 shadow-lg group-hover:scale-105 transition-transform duration-300"
                 style="width: 48px; height: 48px;">
              <UserIcon class="text-white w-5 h-5" />
            </div>
            <div v-if="!sidebarCollapsed" class="flex-grow">
              <div class="font-semibold text-white">{{ user?.name || 'Admin User' }}</div>
              <div class="text-white/60 text-sm">{{ user?.email || 'admin@example.com' }}</div>
            </div>
            <ChevronUpIcon v-if="!sidebarCollapsed && showUserMenu" class="ml-2 w-4 h-4 text-white/60 transition-transform duration-300" />
            <ChevronDownIcon v-if="!sidebarCollapsed && !showUserMenu" class="ml-2 w-4 h-4 text-white/60 transition-transform duration-300" />
          </button>
          
          <!-- User Menu Dropdown -->
          <div v-if="showUserMenu" class="absolute bottom-full left-0 right-0 mb-2 glass rounded-2xl shadow-glass border border-white/20 overflow-hidden animate-slide-up">
            <div class="py-2">
              <a class="flex items-center px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-200" href="#" @click.prevent="handleProfile">
                <UserIcon class="mr-3 w-4 h-4" />
                <span class="font-medium">Profile</span>
              </a>
              <a class="flex items-center px-4 py-3 text-white/80 hover:text-white hover:bg-white/10 transition-all duration-200" href="#" @click.prevent="handleSettings">
                <CogIcon class="mr-3 w-4 h-4" />
                <span class="font-medium">Settings</span>
              </a>
              <div class="border-t border-white/10 my-2"></div>
              <a class="flex items-center px-4 py-3 text-red-300 hover:text-red-200 hover:bg-red-500/10 transition-all duration-200" href="#" @click.prevent="handleLogout">
                <ArrowRightOnRectangleIcon class="mr-3 w-4 h-4" />
                <span class="font-medium">Logout</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- Main Content Area -->
    <div class="main-content flex-grow transition-all duration-300" :class="{ 'sidebar-collapsed': sidebarCollapsed }">
      <!-- Top Header -->
      <header class="header glass backdrop-blur-xl border-b border-white/10 sticky top-0 z-40">
        <div class="w-full px-6">
          <div class="flex items-center justify-between py-4">
            <div class="flex items-center">
              <button 
                class="text-gray-700 p-2 mr-4 lg:hidden hover:text-gray-900 hover:bg-white/10 rounded-xl transition-all duration-200"
                @click="toggleSidebar"
              >
                <Bars3Icon class="w-6 h-6" />
              </button>
              <button 
                class="text-gray-700 p-2 mr-4 hidden lg:block hover:text-gray-900 hover:bg-white/10 rounded-xl transition-all duration-200"
                @click="toggleSidebar"
              >
                <Bars3Icon class="w-6 h-6" />
              </button>
              <div>
                <h1 class="text-2xl font-bold text-gray-800 mb-0">{{ pageTitle }}</h1>
                <p class="text-gray-600 text-sm">{{ pageSubtitle }}</p>
              </div>
            </div>
            <div class="flex items-center space-x-4">
                <!-- Notifications -->
                <div class="relative">
                  <button 
                    class="text-gray-700 p-3 relative hover:text-gray-900 hover:bg-white/10 rounded-2xl transition-all duration-200 group"
                    @click="toggleNotifications"
                  >
                    <BellIcon class="w-5 h-5" />
                    <span class="absolute -top-1 -right-1 bg-gradient-to-r from-red-500 to-pink-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center font-semibold shadow-lg animate-pulse">
                      3
                    </span>
                  </button>
                  <div v-if="showNotifications" class="absolute right-0 mt-2 w-80 glass rounded-2xl shadow-glass border border-white/20 z-50 overflow-hidden animate-slide-down">
                    <div class="p-4 border-b border-white/10">
                      <h6 class="font-semibold text-gray-800">Notifications</h6>
                    </div>
                    <div class="py-2">
                      <a class="block px-4 py-3 text-gray-700 hover:bg-white/10 transition-all duration-200 border-l-4 border-transparent hover:border-blue-500" href="#">
                        <div class="font-medium">New user registered</div>
                        <div class="text-sm text-gray-500">2 minutes ago</div>
                      </a>
                      <a class="block px-4 py-3 text-gray-700 hover:bg-white/10 transition-all duration-200 border-l-4 border-transparent hover:border-green-500" href="#">
                        <div class="font-medium">Role permissions updated</div>
                        <div class="text-sm text-gray-500">5 minutes ago</div>
                      </a>
                      <a class="block px-4 py-3 text-gray-700 hover:bg-white/10 transition-all duration-200 border-l-4 border-transparent hover:border-purple-500" href="#">
                        <div class="font-medium">System backup completed</div>
                        <div class="text-sm text-gray-500">1 hour ago</div>
                      </a>
                      <div class="border-t border-white/10 my-2"></div>
                      <a class="block px-4 py-3 text-center text-blue-600 hover:bg-blue-50 transition-all duration-200 font-medium" href="#">View all notifications</a>
                    </div>
                  </div>
                </div>

                <!-- User Menu -->
                <div class="relative">
                  <button 
                    class="text-gray-700 p-2 flex items-center hover:text-gray-900 hover:bg-white/10 rounded-2xl transition-all duration-200 group"
                    @click="toggleHeaderUserMenu"
                  >
                    <div class="user-avatar gradient-primary rounded-2xl flex items-center justify-center mr-3 shadow-lg group-hover:scale-105 transition-transform duration-300"
                         style="width: 40px; height: 40px;">
                      <UserIcon class="text-white w-5 h-5" />
                    </div>
                    <div class="hidden md:block text-left">
                      <div class="font-semibold text-gray-800">{{ user?.name || 'Admin User' }}</div>
                      <div class="text-sm text-gray-600">{{ user?.email || 'admin@example.com' }}</div>
                    </div>
                    <ChevronDownIcon class="ml-2 w-4 h-4 text-gray-600 group-hover:text-gray-800 transition-colors duration-200" />
                  </button>
                  <div v-if="showHeaderUserMenu" class="absolute right-0 mt-2 w-56 glass rounded-2xl shadow-glass border border-white/20 z-50 overflow-hidden animate-slide-down">
                    <div class="py-2">
                      <a class="flex items-center px-4 py-3 text-gray-700 hover:text-gray-900 hover:bg-white/10 transition-all duration-200" href="#" @click.prevent="handleProfile">
                        <UserIcon class="mr-3 w-4 h-4" />
                        <span class="font-medium">Profile</span>
                      </a>
                      <a class="flex items-center px-4 py-3 text-gray-700 hover:text-gray-900 hover:bg-white/10 transition-all duration-200" href="#" @click.prevent="handleSettings">
                        <CogIcon class="mr-3 w-4 h-4" />
                        <span class="font-medium">Settings</span>
                      </a>
                      <div class="border-t border-white/10 my-2"></div>
                      <a class="flex items-center px-4 py-3 text-red-600 hover:text-red-700 hover:bg-red-50 transition-all duration-200" href="#" @click.prevent="handleLogout">
                        <ArrowRightOnRectangleIcon class="mr-3 w-4 h-4" />
                        <span class="font-medium">Logout</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </header>

      <!-- Page Content -->
      <main class="content p-4">
        <slot />
      </main>
    </div>

    <!-- Mobile Sidebar Overlay -->
    <div 
      v-if="showMobileOverlay" 
      class="sidebar-overlay lg:hidden"
      @click="closeSidebar"
    ></div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAuth } from '../../composables/useAuth';
import {
  Bars3Icon,
  XMarkIcon,
  HomeIcon,
  UsersIcon,
  UserGroupIcon,
  KeyIcon,
  UserIcon,
  BellIcon,
  CogIcon,
  ArrowRightOnRectangleIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ShieldCheckIcon
} from '@heroicons/vue/24/outline';

const route = useRoute();
const router = useRouter();
const { user, logout, hasPermission } = useAuth();

const sidebarCollapsed = ref(false);
const showMobileOverlay = ref(false);
const showUserMenu = ref(false);
const showNotifications = ref(false);
const showHeaderUserMenu = ref(false);

const pageTitle = computed(() => {
  const titles = {
    '/dashboard': 'Dashboard',
    '/users': 'User Management',
    '/roles': 'Role Management',
    '/permissions': 'Permission Management'
  };
  return titles[route.path] || 'Admin Panel';
});

const pageSubtitle = computed(() => {
  const subtitles = {
    '/dashboard': 'Overview of your system',
    '/users': 'Manage system users',
    '/roles': 'Manage user roles',
    '/permissions': 'Manage system permissions'
  };
  return subtitles[route.path] || 'Manage your system';
});

const toggleSidebar = () => {
  sidebarCollapsed.value = !sidebarCollapsed.value;
  if (window.innerWidth < 992) {
    showMobileOverlay.value = !sidebarCollapsed.value;
  }
};

const closeSidebar = () => {
  if (window.innerWidth < 992) {
    sidebarCollapsed.value = true;
    showMobileOverlay.value = false;
  }
};

const handleProfile = () => {
  // Navigate to profile page
  router.push('/profile');
};

const handleSettings = () => {
  // Navigate to settings page
  router.push('/settings');
};

const handleLogout = async () => {
  await logout();
  router.push('/login');
};

const toggleUserMenu = () => {
  showUserMenu.value = !showUserMenu.value;
  showNotifications.value = false;
  showHeaderUserMenu.value = false;
};

const toggleNotifications = () => {
  showNotifications.value = !showNotifications.value;
  showUserMenu.value = false;
  showHeaderUserMenu.value = false;
};

const toggleHeaderUserMenu = () => {
  showHeaderUserMenu.value = !showHeaderUserMenu.value;
  showUserMenu.value = false;
  showNotifications.value = false;
};

const handleResize = () => {
  if (window.innerWidth >= 992) {
    showMobileOverlay.value = false;
  }
};

onMounted(() => {
  window.addEventListener('resize', handleResize);
  // Auto-collapse sidebar on mobile
  if (window.innerWidth < 992) {
    sidebarCollapsed.value = true;
  }
});

onUnmounted(() => {
  window.removeEventListener('resize', handleResize);
});
</script>

<style scoped>
@reference "../../style.css";

/* Sidebar Styles */
.sidebar {
  width: 280px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 1000;
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
}

.sidebar.collapsed {
  width: 80px;
}

.sidebar-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(4px);
  z-index: 999;
  animation: fadeIn 0.3s ease;
}

/* Main Content */
.main-content {
  margin-left: 280px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  min-height: 100vh;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
}

.main-content.sidebar-collapsed {
  margin-left: 80px;
}

/* Header Styles */
.header {
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.15);
  border-bottom: 1px solid rgba(255, 255, 255, 0.18);
}

/* Navigation Icons */
.nav-icon-wrapper {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.nav-link:hover .nav-icon-wrapper {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

/* User Avatar */
.user-avatar {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

/* Brand Icon */
.brand-icon {
  min-width: 48px;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.brand-icon:hover {
  transform: rotate(5deg) scale(1.05);
}

/* Mobile Responsive */
@media (max-width: 1023px) {
  .sidebar {
    transform: translateX(-100%);
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
  }
  
  .sidebar:not(.collapsed) {
    transform: translateX(0);
  }
  
  .main-content {
    margin-left: 0;
  }
  
  .main-content.sidebar-collapsed {
    margin-left: 0;
  }
}

/* Hide text when sidebar is collapsed */
.sidebar.collapsed .brand-text,
.sidebar.collapsed span:not(.notification-badge) {
  display: none;
}

.sidebar.collapsed .nav-icon-wrapper {
  margin-right: 0;
}

/* Content Area */
.content {
  background: transparent;
  min-height: calc(100vh - 80px);
}

/* Custom Animations */
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-slide-up {
  animation: slideUp 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.animate-slide-down {
  animation: slideDown 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

/* Hover Effects */
.nav-link {
  position: relative;
  overflow: hidden;
}

.nav-link::before {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
  transition: left 0.5s;
}

.nav-link:hover::before {
  left: 100%;
}

/* Scrollbar Styling */
.sidebar-content::-webkit-scrollbar {
  width: 4px;
}

.sidebar-content::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 2px;
}

.sidebar-content::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 2px;
}

.sidebar-content::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}

/* Glass Effect Enhancement */
.glass {
  background: rgba(255, 255, 255, 0.25);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.18);
}

.glass-dark {
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.shadow-glass {
  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.37);
}

/* Notification Badge Animation */
@keyframes pulse {
  0%, 100% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.1);
  }
}

.animate-pulse {
  animation: pulse 2s infinite;
}
</style>

// frontend/src/components/layout/Navigation.jsx
import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import {
  Bars3Icon,
  XMarkIcon,
  UserIcon,
  UsersIcon,
  ShieldCheckIcon,
  KeyIcon,
  HomeIcon,
  ArrowRightOnRectangleIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
} from '@heroicons/react/24/outline';

const Navigation = ({ onToggle }) => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const { user, logout, isAdmin } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  const { hasPermission } = useAuth();

  const navigation = [
    { name: 'Dashboard', href: '/dashboard', icon: HomeIcon, current: location.pathname === '/dashboard' },
    ...(hasPermission('view users') || isAdmin() ? [
      { name: 'Users', href: '/users', icon: UsersIcon, current: location.pathname === '/users' }
    ] : []),
    ...(hasPermission('view roles') || isAdmin() ? [
      { name: 'Roles', href: '/roles', icon: ShieldCheckIcon, current: location.pathname === '/roles' }
    ] : []),
    ...(hasPermission('view permissions') || isAdmin() ? [
      { name: 'Permissions', href: '/permissions', icon: KeyIcon, current: location.pathname === '/permissions' }
    ] : []),
  ];

  return (
    <div className={`position-fixed top-0 start-0 bottom-0 ${isCollapsed ? 'sidebar-collapsed' : 'sidebar-expanded'} transition-all`} style={{zIndex: 1050}}>
      {/* Sidebar */}
      <div className="d-flex flex-column h-100 sidebar-gradient shadow-lg">
        {/* Header */}
        <div className="d-flex align-items-center justify-content-between p-3 border-bottom border-secondary border-opacity-25">
          {!isCollapsed && (
            <div className="d-flex align-items-center gap-3">
              <div className="d-flex align-items-center justify-content-center primary-gradient rounded-3" style={{width: '2rem', height: '2rem'}}>
                <span className="text-white fw-bold small">A</span>
              </div>
              <h1 className="h5 fw-bold text-white mb-0">
                Admin Panel
              </h1>
            </div>
          )}
          <button
            onClick={() => {
              const newCollapsed = !isCollapsed;
              setIsCollapsed(newCollapsed);
              onToggle?.(newCollapsed);
            }}
            className="btn btn-outline-light btn-sm rounded-3 hover-scale"
            style={{border: 'none', backgroundColor: 'rgba(255,255,255,0.1)'}}
          >
            {isCollapsed ? (
              <ChevronRightIcon style={{width: '1.25rem', height: '1.25rem'}} />
            ) : (
              <ChevronLeftIcon style={{width: '1.25rem', height: '1.25rem'}} />
            )}
          </button>
        </div>

        {/* Navigation Links */}
        <nav className="flex-grow-1 px-3 py-4">
          <div className="d-flex flex-column gap-2">
            {navigation.map((item) => (
              <Link
                key={item.name}
                to={item.href}
                className={`d-flex align-items-center px-3 py-3 text-decoration-none rounded-3 transition-all hover-lift ${
                  item.current
                    ? 'primary-gradient text-white shadow-sm'
                    : 'text-light hover-bg-light'
                }`}
                style={{
                  backgroundColor: item.current ? '' : 'transparent'
                }}
              >
                <item.icon 
                  className={`${isCollapsed ? 'mx-auto' : 'me-3'} ${
                    item.current ? 'text-white' : 'text-light'
                  }`}
                  style={{width: '1.25rem', height: '1.25rem'}}
                />
                {!isCollapsed && (
                  <span className="fw-medium">{item.name}</span>
                )}
                {item.current && !isCollapsed && (
                  <div className="ms-auto bg-white rounded-circle" style={{width: '0.5rem', height: '0.5rem'}}></div>
                )}
              </Link>
            ))}
          </div>
        </nav>

        {/* User Profile Section */}
        <div className="border-top border-secondary border-opacity-25 p-3">
          <div className="position-relative">
            <button
              onClick={() => setUserMenuOpen(!userMenuOpen)}
              className={`btn w-100 d-flex align-items-center ${isCollapsed ? 'justify-content-center' : ''} p-3 rounded-3 shadow-lg`}
              style={{
                backgroundColor: 'rgba(255,255,255,0.08)',
                backdropFilter: 'blur(10px)',
                border: '1px solid rgba(255,255,255,0.1)',
                gap: isCollapsed ? '0' : '0.75rem'
              }}
            >
              <div className="d-flex align-items-center justify-content-center primary-gradient rounded-circle flex-shrink-0 shadow-lg" 
                   style={{
                     width: '2.5rem', 
                     height: '2.5rem',
                     background: 'linear-gradient(135deg, #3b82f6, #8b5cf6, #ec4899)',
                     boxShadow: '0 0 0 2px rgba(255,255,255,0.2)'
                   }}>
                <UserIcon className="text-white" style={{width: '1.25rem', height: '1.25rem'}} />
              </div>
              {!isCollapsed && (
                <div className="flex-grow-1 text-start">
                  <div className="small fw-bold text-white text-truncate" style={{textShadow: '0 1px 2px rgba(0,0,0,0.1)'}}>{user?.name}</div>
                  <div className="text-light text-truncate opacity-75" style={{fontSize: '0.75rem'}}>{user?.email}</div>
                </div>
              )}
              {!isCollapsed && (
                <div className="flex-shrink-0">
                  <ChevronRightIcon 
                    className="text-light" 
                    style={{
                      width: '1rem', 
                      height: '1rem',
                      transform: userMenuOpen ? 'rotate(90deg)' : 'rotate(0deg)',
                      transition: 'transform 0.2s ease'
                    }} 
                  />
                </div>
              )}
            </button>

            {/* User Dropdown Menu */}
            {userMenuOpen && (
              <div className={`position-absolute ${isCollapsed ? '' : 'end-0'} bg-white rounded-3 shadow-lg border overflow-hidden`} 
                   style={{
                     width: '14rem',
                     bottom: isCollapsed ? '0' : '4rem',
                     left: isCollapsed ? '100%' : 'auto',
                     marginLeft: isCollapsed ? '1rem' : '0',
                     boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
                     zIndex: 1050
                   }}>
                <div className="px-4 py-3 border-bottom" 
                     style={{
                       background: 'linear-gradient(90deg, #eff6ff, #faf5ff)'
                     }}>
                  <div className="small fw-bold text-dark text-truncate">{user?.name}</div>
                  <div className="text-muted text-truncate" style={{fontSize: '0.75rem', marginTop: '0.125rem'}}>{user?.email}</div>
                </div>
                <div className="py-1">
                  <button
                    onClick={handleLogout}
                    className="btn w-100 d-flex align-items-center text-start px-4 py-3 text-secondary border-0 rounded-0"
                    style={{
                      transition: 'all 0.15s ease',
                      gap: '0.75rem'
                    }}
                    onMouseEnter={(e) => {
                      e.target.style.backgroundColor = '#fef2f2';
                      e.target.style.color = '#dc2626';
                    }}
                    onMouseLeave={(e) => {
                      e.target.style.backgroundColor = 'transparent';
                      e.target.style.color = '#6c757d';
                    }}
                  >
                    <ArrowRightOnRectangleIcon 
                      className="text-muted" 
                      style={{width: '1rem', height: '1rem'}} 
                    />
                    <span className="fw-medium">Sign out</span>
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Overlay for mobile */}
      {userMenuOpen && (
        <div 
          className="position-fixed top-0 start-0 w-100 h-100 bg-dark bg-opacity-25" 
          style={{zIndex: 1040}}
          onClick={() => setUserMenuOpen(false)}
        />
      )}
    </div>
  );
};

export default Navigation;
