// frontend/src/components/auth/Register.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { EyeIcon, EyeSlashIcon, LockClosedIcon, EnvelopeIcon, UserIcon, UserPlusIcon } from '@heroicons/react/24/outline';

const Register = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
  });
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [errors, setErrors] = useState({});

  const { register } = useAuth();
  const navigate = useNavigate();

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
    setError('');
    setErrors({});
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setErrors({});

    if (formData.password !== formData.password_confirmation) {
      setError('Passwords do not match');
      setLoading(false);
      return;
    }

    const result = await register(formData);
    
    if (result.success) {
      navigate('/dashboard');
    } else {
      setError(result.message);
      setErrors(result.errors || {});
    }
    
    setLoading(false);
  };

  return (
    <div className="min-vh-100 d-flex align-items-center justify-content-center gradient-bg py-5">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-6 col-lg-4">
            {/* Header */}
            <div className="text-center mb-4">
              <div className="mx-auto mb-4 d-flex align-items-center justify-content-center secondary-gradient rounded-4 shadow-lg" style={{width: '4rem', height: '4rem'}}>
                <UserPlusIcon className="text-white" style={{width: '2rem', height: '2rem'}} />
              </div>
              <h2 className="h3 fw-bold text-dark mb-2">
                Create Account
              </h2>
              <p className="text-muted">
                Join us and start managing your system
              </p>
              <p className="mt-3 small text-muted">
                Already have an account?{' '}
                <Link
                  to="/login"
                  className="fw-semibold text-primary text-decoration-none"
                >
                  Sign in here
                </Link>
              </p>
            </div>

            {/* Form */}
            <div className="card shadow-lg border-0 rounded-4">
              <div className="card-body p-4">
                <form onSubmit={handleSubmit}>
                  {error && (
                    <div className="alert alert-danger d-flex align-items-center rounded-3 mb-4" role="alert">
                      <div className="bg-danger rounded-circle me-2" style={{width: '0.5rem', height: '0.5rem'}}></div>
                      <span className="small fw-medium">{error}</span>
                    </div>
                  )}
                  
                  {/* Name Field */}
                  <div className="mb-3">
                    <label htmlFor="name" className="form-label fw-semibold text-dark">
                      Full Name
                    </label>
                    <div className="position-relative">
                      <div className="position-absolute top-50 start-0 translate-middle-y ps-3">
                        <UserIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                      </div>
                      <input
                        id="name"
                        name="name"
                        type="text"
                        autoComplete="name"
                        required
                        className="form-control ps-5 py-3 rounded-3 border-1"
                        placeholder="Enter your full name"
                        value={formData.name}
                        onChange={handleChange}
                        style={{backgroundColor: 'rgba(248, 249, 250, 0.8)'}}
                      />
                    </div>
                    {errors.name && (
                      <div className="text-danger small mt-1 d-flex align-items-center">
                        <div className="bg-danger rounded-circle me-2" style={{width: '0.25rem', height: '0.25rem'}}></div>
                        <span>{errors.name[0]}</span>
                      </div>
                    )}
                  </div>

                  {/* Email Field */}
                  <div className="mb-3">
                    <label htmlFor="email" className="form-label fw-semibold text-dark">
                      Email Address
                    </label>
                    <div className="position-relative">
                      <div className="position-absolute top-50 start-0 translate-middle-y ps-3">
                        <EnvelopeIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                      </div>
                      <input
                        id="email"
                        name="email"
                        type="email"
                        autoComplete="email"
                        required
                        className="form-control ps-5 py-3 rounded-3 border-1"
                        placeholder="Enter your email address"
                        value={formData.email}
                        onChange={handleChange}
                        style={{backgroundColor: 'rgba(248, 249, 250, 0.8)'}}
                      />
                    </div>
                    {errors.email && (
                      <div className="text-danger small mt-1 d-flex align-items-center">
                        <div className="bg-danger rounded-circle me-2" style={{width: '0.25rem', height: '0.25rem'}}></div>
                        <span>{errors.email[0]}</span>
                      </div>
                    )}
                  </div>

                  {/* Password Field */}
                  <div className="mb-3">
                    <label htmlFor="password" className="form-label fw-semibold text-dark">
                      Password
                    </label>
                    <div className="position-relative">
                      <div className="position-absolute top-50 start-0 translate-middle-y ps-3">
                        <LockClosedIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                      </div>
                      <input
                        id="password"
                        name="password"
                        type={showPassword ? 'text' : 'password'}
                        autoComplete="new-password"
                        required
                        className="form-control ps-5 pe-5 py-3 rounded-3 border-1"
                        placeholder="Enter your password"
                        value={formData.password}
                        onChange={handleChange}
                        style={{backgroundColor: 'rgba(248, 249, 250, 0.8)'}}
                      />
                      <button
                        type="button"
                        className="btn position-absolute top-50 end-0 translate-middle-y pe-3 border-0 bg-transparent"
                        onClick={() => setShowPassword(!showPassword)}
                      >
                        {showPassword ? (
                          <EyeSlashIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                        ) : (
                          <EyeIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                        )}
                      </button>
                    </div>
                    {errors.password && (
                      <div className="text-danger small mt-1 d-flex align-items-center">
                        <div className="bg-danger rounded-circle me-2" style={{width: '0.25rem', height: '0.25rem'}}></div>
                        <span>{errors.password[0]}</span>
                      </div>
                    )}
                  </div>

                  {/* Confirm Password Field */}
                  <div className="mb-4">
                    <label htmlFor="password_confirmation" className="form-label fw-semibold text-dark">
                      Confirm Password
                    </label>
                    <div className="position-relative">
                      <div className="position-absolute top-50 start-0 translate-middle-y ps-3">
                        <LockClosedIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                      </div>
                      <input
                        id="password_confirmation"
                        name="password_confirmation"
                        type={showConfirmPassword ? 'text' : 'password'}
                        autoComplete="new-password"
                        required
                        className="form-control ps-5 pe-5 py-3 rounded-3 border-1"
                        placeholder="Confirm your password"
                        value={formData.password_confirmation}
                        onChange={handleChange}
                        style={{backgroundColor: 'rgba(248, 249, 250, 0.8)'}}
                      />
                      <button
                        type="button"
                        className="btn position-absolute top-50 end-0 translate-middle-y pe-3 border-0 bg-transparent"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      >
                        {showConfirmPassword ? (
                          <EyeSlashIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                        ) : (
                          <EyeIcon className="text-muted" style={{width: '1.25rem', height: '1.25rem'}} />
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Submit Button */}
                  <div className="d-grid">
                    <button
                      type="submit"
                      disabled={loading}
                      className="btn btn-secondary py-3 fw-semibold rounded-3"
                    >
                      {loading ? (
                        <div className="spinner-border spinner-border-sm text-white" role="status">
                          <span className="visually-hidden">Loading...</span>
                        </div>
                      ) : (
                        <span>Create Account</span>
                      )}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;

// vue-frontend/src/components/auth/Register.vue
<template>
  <div class="min-vh-100 d-flex align-items-center justify-content-center gradient-bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
          <div class="card shadow-lg border-0 fade-in" style="border-radius: 1rem;">
            <div class="card-body p-5">
              <!-- Header -->
              <div class="text-center mb-4">
                <div class="d-inline-flex align-items-center justify-content-center rounded-circle bg-success bg-opacity-10 mb-3" 
                     style="width: 4rem; height: 4rem;">
                  <UserPlusIcon class="text-success" style="width: 2rem; height: 2rem;" />
                </div>
                <h2 class="fw-bold text-dark mb-2">Create Account</h2>
                <p class="text-muted">Join us and start managing your system</p>
              </div>

              <!-- Error Alert -->
              <div v-if="error" class="alert alert-danger d-flex align-items-center mb-4" role="alert">
                <ExclamationTriangleIcon class="me-2 flex-shrink-0" style="width: 20px; height: 20px;" />
                {{ error }}
              </div>

              <!-- Register Form -->
              <form @submit.prevent="handleSubmit">
                <!-- Name Field -->
                <div class="mb-3">
                  <label for="name" class="form-label fw-medium text-dark">Full Name</label>
                  <div class="position-relative">
                    <div class="position-absolute top-50 start-0 translate-middle-y ms-3">
                      <UserIcon class="text-muted" style="width: 20px; height: 20px;" />
                    </div>
                    <input
                      id="name"
                      v-model="formData.name"
                      type="text"
                      class="form-control ps-5 py-3"
                      :class="{ 'is-invalid': errors.name }"
                      placeholder="Enter your full name"
                      required
                      style="border-radius: 0.75rem; border: 2px solid #e9ecef;"
                    />
                    <div v-if="errors.name" class="invalid-feedback">
                      {{ errors.name[0] }}
                    </div>
                  </div>
                </div>

                <!-- Email Field -->
                <div class="mb-3">
                  <label for="email" class="form-label fw-medium text-dark">Email Address</label>
                  <div class="position-relative">
                    <div class="position-absolute top-50 start-0 translate-middle-y ms-3">
                      <EnvelopeIcon class="text-muted" style="width: 20px; height: 20px;" />
                    </div>
                    <input
                      id="email"
                      v-model="formData.email"
                      type="email"
                      class="form-control ps-5 py-3"
                      :class="{ 'is-invalid': errors.email }"
                      placeholder="Enter your email"
                      required
                      style="border-radius: 0.75rem; border: 2px solid #e9ecef;"
                    />
                    <div v-if="errors.email" class="invalid-feedback">
                      {{ errors.email[0] }}
                    </div>
                  </div>
                </div>

                <!-- Password Field -->
                <div class="mb-3">
                  <label for="password" class="form-label fw-medium text-dark">Password</label>
                  <div class="position-relative">
                    <div class="position-absolute top-50 start-0 translate-middle-y ms-3">
                      <LockClosedIcon class="text-muted" style="width: 20px; height: 20px;" />
                    </div>
                    <input
                      id="password"
                      v-model="formData.password"
                      :type="showPassword ? 'text' : 'password'"
                      class="form-control ps-5 pe-5 py-3"
                      :class="{ 'is-invalid': errors.password }"
                      placeholder="Enter your password"
                      required
                      style="border-radius: 0.75rem; border: 2px solid #e9ecef;"
                    />
                    <button
                      type="button"
                      class="btn position-absolute top-50 end-0 translate-middle-y me-3 p-0 border-0 bg-transparent"
                      @click="showPassword = !showPassword"
                    >
                      <EyeIcon v-if="!showPassword" class="text-muted" style="width: 20px; height: 20px;" />
                      <EyeSlashIcon v-else class="text-muted" style="width: 20px; height: 20px;" />
                    </button>
                    <div v-if="errors.password" class="invalid-feedback">
                      {{ errors.password[0] }}
                    </div>
                  </div>
                </div>

                <!-- Confirm Password Field -->
                <div class="mb-4">
                  <label for="password_confirmation" class="form-label fw-medium text-dark">Confirm Password</label>
                  <div class="position-relative">
                    <div class="position-absolute top-50 start-0 translate-middle-y ms-3">
                      <LockClosedIcon class="text-muted" style="width: 20px; height: 20px;" />
                    </div>
                    <input
                      id="password_confirmation"
                      v-model="formData.password_confirmation"
                      :type="showConfirmPassword ? 'text' : 'password'"
                      class="form-control ps-5 pe-5 py-3"
                      :class="{ 'is-invalid': errors.password_confirmation }"
                      placeholder="Confirm your password"
                      required
                      style="border-radius: 0.75rem; border: 2px solid #e9ecef;"
                    />
                    <button
                      type="button"
                      class="btn position-absolute top-50 end-0 translate-middle-y me-3 p-0 border-0 bg-transparent"
                      @click="showConfirmPassword = !showConfirmPassword"
                    >
                      <EyeIcon v-if="!showConfirmPassword" class="text-muted" style="width: 20px; height: 20px;" />
                      <EyeSlashIcon v-else class="text-muted" style="width: 20px; height: 20px;" />
                    </button>
                    <div v-if="errors.password_confirmation" class="invalid-feedback">
                      {{ errors.password_confirmation[0] }}
                    </div>
                  </div>
                </div>

                <!-- Submit Button -->
                <button
                  type="submit"
                  class="btn btn-success w-100 py-3 fw-semibold"
                  :disabled="loading"
                  style="border-radius: 0.75rem; background: var(--success-gradient); border: none;"
                >
                  <span v-if="loading" class="spinner-border spinner-border-sm me-2" role="status"></span>
                  {{ loading ? 'Creating Account...' : 'Create Account' }}
                </button>
              </form>

              <!-- Login Link -->
              <div class="text-center mt-4">
                <p class="text-muted mb-0">
                  Already have an account? 
                  <router-link to="/login" class="text-decoration-none fw-medium">
                    Sign in here
                  </router-link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../../composables/useAuth';
import { 
  EyeIcon, 
  EyeSlashIcon, 
  LockClosedIcon, 
  EnvelopeIcon,
  UserIcon,
  UserPlusIcon,
  ExclamationTriangleIcon 
} from '@heroicons/vue/24/outline';

const router = useRouter();
const { register } = useAuth();

const formData = reactive({
  name: '',
  email: '',
  password: '',
  password_confirmation: '',
});

const showPassword = ref(false);
const showConfirmPassword = ref(false);
const loading = ref(false);
const error = ref('');
const errors = ref({});

const handleSubmit = async () => {
  loading.value = true;
  error.value = '';
  errors.value = {};

  try {
    const result = await register(formData);
    
    if (result.success) {
      router.push('/dashboard');
    } else {
      error.value = result.error;
      if (result.errors) {
        errors.value = result.errors;
      }
    }
  } catch (err) {
    error.value = 'An unexpected error occurred. Please try again.';
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.form-control:focus {
  border-color: #4facfe;
  box-shadow: 0 0 0 0.2rem rgba(79, 172, 254, 0.25);
}

.btn-success:hover {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(79, 172, 254, 0.4);
}

.card {
  backdrop-filter: blur(10px);
  background: rgba(255, 255, 255, 0.95);
}
</style>
